# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'en\ui_loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(450, 300)
        LoginWindow.setWindowTitle("")
        LoginWindow.setStyleSheet("color: rgb(187, 187, 187);\n"
"background-color: rgb(60, 63, 65);")
        self.lineEdit_id = QtWidgets.QLineEdit(LoginWindow)
        self.lineEdit_id.setGeometry(QtCore.QRect(160, 64, 191, 24))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(80, 64, 45, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoginWindow)
        self.label_2.setGeometry(QtCore.QRect(80, 120, 45, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_password = QtWidgets.QLineEdit(LoginWindow)
        self.lineEdit_password.setGeometry(QtCore.QRect(160, 120, 191, 24))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.login_button = QtWidgets.QPushButton(LoginWindow)
        self.login_button.setGeometry(QtCore.QRect(90, 190, 251, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(150, 150, 150);")
        self.login_button.setObjectName("login_button")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("LoginWindow", "Account"))
        self.label_2.setText(_translate("LoginWindow", "Password"))
        self.login_button.setText(_translate("LoginWindow", "Login"))
        self.login_button.setShortcut(_translate("LoginWindow", "Return"))
