# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'en\ui_classWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassWindow(object):
    def setupUi(self, ClassWindow):
        ClassWindow.setObjectName("ClassWindow")
        ClassWindow.resize(300, 300)
        ClassWindow.setStyleSheet("color: rgb(187, 187, 187);\n"
"background-color: rgb(60, 63, 65);")
        self.lineEdit_class = QtWidgets.QLineEdit(ClassWindow)
        self.lineEdit_class.setGeometry(QtCore.QRect(9, 10, 281, 20))
        self.lineEdit_class.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_class.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_class.setObjectName("lineEdit_class")
        self.listView_classes = QtWidgets.QListView(ClassWindow)
        self.listView_classes.setGeometry(QtCore.QRect(9, 76, 281, 221))
        self.listView_classes.setStyleSheet("color: rgb(255, 255, 255);")
        self.listView_classes.setObjectName("listView_classes")
        self.layoutWidget = QtWidgets.QWidget(ClassWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(94, 40, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ok_button = QtWidgets.QPushButton(self.layoutWidget)
        self.ok_button.setStyleSheet("background-color: rgb(100,100,100);")
        self.ok_button.setObjectName("ok_button")
        self.gridLayout.addWidget(self.ok_button, 0, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(self.layoutWidget)
        self.cancel_button.setStyleSheet("background-color: rgb(100,100,100);")
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 0, 1, 1, 1)

        self.retranslateUi(ClassWindow)
        QtCore.QMetaObject.connectSlotsByName(ClassWindow)

    def retranslateUi(self, ClassWindow):
        _translate = QtCore.QCoreApplication.translate
        ClassWindow.setWindowTitle(_translate("ClassWindow", "Select Defect"))
        self.ok_button.setText(_translate("ClassWindow", "OK"))
        self.cancel_button.setText(_translate("ClassWindow", "Cancel"))
